blog/urls.py
from django.urls import path
from .views import (NewsList, NewsDetail,
                    NewsCreate, NewsUpdate,
                    NewsDelete, NewsSearch,
                    ArticleCreate, ArticleUpdate,
                    ArticleDelete, CategoriListView, subscrib)
# from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', NewsList.as_view(), name='news_list'),
    path('<int:pk>/', NewsDetail.as_view(), name='news-details'),
    path('create/', NewsCreate.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='news_edit'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('search/', NewsSearch.as_view(), name='news_search'),
    path('cre/', ArticleCreate.as_view(), name='article_create'),
    path('<int:pk>/edit/', ArticleUpdate.as_view(), name='article_edit'),
    path('<int:pk>/del/', ArticleDelete.as_view(), name='article_delete'),
    path('categories/<int:pk>', CategoriListView.as_view(), name='categori_list'),
    path('categories/<int:pk>/subscribe/', subscrib, name='subscribe'),
    # path('', set_timezone, name='set_timezone'),

]

pet_proj_dj/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers

from blog import views

router = routers.DefaultRouter()
router.register(r'news', views.NewsViewset)
router.register(r'user', views.UserViewset)
router.register(r'author', views.AuthorViewset)
router.register(r'categories', views.CategoriesViewset)

schema_view = get_schema_view(
    openapi.Info(
        title="Your API title",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(),
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('blog.urls')),
    path('article/', include('blog.urls')),
    path("accounts/", include("allauth.urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/', include(router.urls), name='api')
]

blog/models.py
from django.db import models
from datetime import datetime
from django.db.models import Sum
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.urls import reverse


# Таблица с сущностью автора
class Author(models.Model):
    full_name = models.CharField(max_length=150)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    # Обновление рейтинга автора на основании лайков и дизлайков
    def update_rating(self):
        news_rat = News.objects.aggregate(rat_a=Sum('rating'))
        n_rat = news_rat.get('rat_a')

        comment_rat = Comment.objects.aggregate(rat_c=Sum('rating'))
        c_rat = comment_rat.get('rat_c')

        self.rating = n_rat * 3 + c_rat
        self.save()

    def __str__(self):
        return f'{self.user}, {self.full_name}, {self.rating}'


# Промежуточная таблица для новостей и категорий
class NewsCategories(models.Model):
    new_key = models.ForeignKey('News', on_delete=models.CASCADE)
    cat_key = models.ForeignKey('Categories', on_delete=models.CASCADE)


# Категории
class Categories(models.Model):
    title = models.CharField(max_length=250, unique=True)
    subscribes = models.ManyToManyField(User, related_name='categories')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title.title()


# Новости
class News(models.Model):
    time = models.DateTimeField(auto_now=False, auto_now_add=True)
    title = models.CharField(max_length=50)
    article = models.TextField()
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новости'),
        (ARTICLE, 'Статья'),
    )
    article_or_news = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=NEWS)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    new_cat = models.ManyToManyField(Categories, through='NewsCategories')
    rating = models.IntegerField(blank=False, default=0)

    # Время добавления
    def date(self):
        # self.time = datetime.strftime('%d.%m.%Y')
        self.time = datetime.now()
        self.save()

    # Лайки и дизлайки новостей
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    # Превью новости
    def preview(self):
        if len(self.article) > 124:
            return f'{self.article[:124]}...'
        return f'{self.article}'

    def __str__(self):
        return f'{self.time.date()}, {self.title.title()}: {self.article}, {self.title.title()}: {self.new_cat}'

    def get_absolute_url(self):
        return reverse('news-details', args=[str(self.id)])


# Таблица с комментариями
class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time = models.DateTimeField(auto_now=False, auto_now_add=True)
    rating = models.IntegerField(blank=False, default=0)

    # Время добавления
    def date(self):
        self.time = datetime.now()
        self.save()

    # Лайки и дизлайки новостей
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.time.date()}, {self.user}, {self.text}, {self.rating}'

templates/article_create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'New article' %}</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-sm mt-1 mb-1" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/article_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}!
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Deleting an article' %}</legend>
                <h2>{% trans 'Are you sure you want to delete this entry?' %}"{{ news.title }}"</h2>
                <p>{{ news.article|truncatewords:5 }}</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">{% trans 'Yes, I want to delete' %}</button>
                <a class="btn btn-outline-secondary" href="{% url 'news-details' news.pk %}">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/article_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Edit article' %}</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-sm mt-1 mb-1" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/categori_list.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}!
<!-- Подключаем новый файл с нашим тегом -->

{% load custom_tags %}
<!-- Название у нас будет Product -->
{% block title %}
    {% trans 'News' %}
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
        {% if is_not_subscriber %}
            <p class="text-capitalize"><a href="{% url 'subscribe' new_cat.id %}" class="btn-secondary btn-sm">{% trans 'Subscribe' %}</a></p>
        {% endif %}
    <hr>
    <ul class="list-group list-group-flush">
        {% for category in categori_news_list %}
            <li class="list-group-item">
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <small class="text-muted">{{ category.time|date:'d.m.Y H:i' }}</small>
                            <small class="text-muted">({% trans 'author' %}: {{ category.author.full_name }})</small>
                            <p>{% for cat in category.new_cat.all %}
                                <small class="fw-bold">{% trans 'category' %}: <a
                                        href="{% url 'categori_list' cat.id %}">{{ new_cat }}</a></small>
                            {% endfor %}</p>
                            <a href="{% url 'news-details' category.pk %}">{{ category.title }}</a>
                            <p>{{ category.article|truncatechars:200 }}</p>

                        </div>
                    </div>
                </article>
            </li>
        {% endfor %}

        </table>
    </ul>
{% endblock content %}


{#{% for categori_news in categori_news_list %}#}
{#<div class="media-body">#}
{#    <div class="article-metadata">#}
{#        <small class="text-muted">{{ art_views.time|date:'d.m.Y H:i' }}</small>#}
{#        <small class="text-muted">автор: {{ categori_news.author.full_name }}</small><br>#}
{#        <small class="fw-bold">категория:#}
{#            <p>{% for cat in categori_news.new_cat.all %}#}
{#                <a href="{% url 'categori_list' cat.id %}">{{ new_cat }}</a>#}
{#            {% endfor %}</p></small>#}
{#        <a href="{% url 'news-details' categori_news.id %}">{{ categori_news.title }}</a>#}

templates/daily_post.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Title' %}</title>
</head>
<body>
<h2>{% trans 'Hello! New articles in the last week' %}</h2>
<ul>
    {% for post in news %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filters %}
{% load custom_tags %}
<!-- Название у нас будет Product -->
{% block title %}
    News
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <small class="text-muted">{{ art_views.time|date:'d.m.Y H:i' }}</small>
                <small class="text-muted">({% trans 'author' %}: {{ art_views.author.full_name }})</small><br>
                <p>{% for cat in art_views.new_cat.all %}
                    <small class="fw-bold">{% trans 'category' %}: <a
                            href="{% url 'categori_list' cat.id %}">{{ cat.title }}</a></small>
                {% endfor %}</p>
                <h2 class="article-title">{{ art_views.title }}</h2>
                <p class="article-content">{{ art_views.article|censor }}</p>
                <hr>
                {% if perms.blog.change_news %}
                    <form action={% url 'news_edit' art_views.pk %}>
                        <div class="form-group">
                            <button class="btn btn-secondary btn-sm mt-1 mb-1"
                                    type="submit">{% translate 'Edit news' %}</button>
                        </div>
                    </form>
                {% endif %}
                <br>
                {% if perms.blog.delete_news %}
                    <form action={% url 'news_delete' art_views.pk %}>
                        <div class="form-group">
                            <button class="btn btn-danger btn-sm mt-1 mb-1"
                                    type="submit">{% translate 'Delete news' %}</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </article>
{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    {% trans 'News' %}
{% endblock title %}

{% block content %}
    <h1>{% trans 'News for today' %}</h1>

    <!-- <h3>{{ time_now|date:'d M Y l' }}</h3> -->
    <br>
    <h3>{% current_time '%d.%m.%Y %A' %}</h3>
    <h3> {{ next_sale|default_if_none:"We follow the news!" }} </h3>

    <hr>
    {% if articleviews %}
        <ul class="list-group">
            {% for news in articleviews %}
                <li class="list-group-item">
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <small class="text-muted">{{ news.time|date:'d.m.Y H:i' }}</small>
                                <small class="text-muted">({% trans 'author' %}: {{ news.author.full_name }})</small><br>
                                <p>{% for cat in news.new_cat.all %}
                                    <small class="fw-bold">{% trans 'category' %}: <a
                                            href="{% url 'categori_list' cat.id %}">{{ cat.title }}</a></small>
                                {% endfor %}</p>
                                <p class="article-title"><a href="{% url 'news-details' news.pk %}">{{ news.title }}</a>
                                </p>
                                <p class="article-content">{{ news.article|truncatechars:200|censor }}</p>
                            </div>
                        </div>
                    </article>
                </li>
            {% endfor %}

            </table>
        </ul>
    {% else %}
        <h2>{% trans 'No news!' %}</h2>
    {% endif %}
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/news_create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filters %}
{% load custom_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'New article' %}</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-sm mt-1 mb-1" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/news_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filters %}
{% load custom_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Deleting an article' %}</legend>
                <h2>{% trans 'Are you sure you want to delete this entry?' %}"{{ news.title }}"</h2>
                <p>{{ news.article|truncatewords:5 }}</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">{% trans 'Yes, I want to delete' %}</button>
                <a class="btn btn-outline-secondary" href="{% url 'news-details' news.pk %}">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/news_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{% trans 'Edit article' %}</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-secondary btn-sm mt-1 mb-1" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/news_search.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->

{% load custom_tags %}!

{% block content %}
    <br>
    {##}
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="{% trans 'Find' %}">
    </form>

    <h1>{% trans 'Search results' %}</h1>
    {% if articlesearch %}
        <table>
            {% for art in articlesearch %}
                <article>
                    <div>
                        <h6>{{ art.time|date:'d.m.Y H:i' }}</h6>
                        <h4>{{ art.title }}</h4>
                    </div>
                    <form action={{ art.get_absolute_url }}>
                        <input type="submit" value="{% trans 'Read more' %}">
                    </form>
                    <hr>
                </article>
            {% empty %}
                <p>{% trans 'No publications found for your query' %}<br>{% trans 'Try again with a different wording' %}</p>
            {% endfor %}
        </table>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans 'Document' %}</title>
</head>
<body>
<h2>{% trans 'Hello! New' %} <a href="{{ link }}">{% trans 'article' %}</a> {% trans 'in your favorite section' %}</h2>
<ul>
    {{ text }}
</ul>
</body>
</html>

templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }} {{ categori }}</h1>
{% endblock content %}

{#{% extends 'flatpages/default.html' %}#}
{##}
{#{% block title %}#}
{#Subscriptions#}
{#{% endblock title %}#}
{##}
{#{% block content %}#}
{#    {% for category in categori  %}#}
{#        <p>#}
{#            {{ category.title }}#}
{#            <form method="post">#}
{#                {% csrf_token %}#}
{#                <input type="hidden" name="category_id" value="{{ category.id }}" />#}
{##}
{#                {% if category.title %}#}
{#                    <button disabled>Подписаться</button>#}
{#                    <button name="action" value="unsubscribe">Отписаться</button>#}
{#                {% else %}#}
{#                    <button name="action" value="subscribe">Подписаться</button>#}
{#                    <button disabled>Отписаться</button>#}
{#                {% endif %}#}
{#            </form>#}
{#        </p>#}
{#    {% endfor %}#}
{#{% endblock content %}#}

templates/swagger-ui.html
<!DOCTYPE html>
{% load custom_tags %}
{% load i18n %}
{% load tz %}
{% load cache %}
<html lang="en">
<head>
    <title>Swagger</title>
    <meta
            charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css"/>
</head>
<body>
<div id="swagger-ui"></div>
<script src="//unpkg.com/swagger-ui-dist@3.52.5/swagger-ui-bundle.js"></script>
<script>
    const ui = SwaggerUIBundle({
        url: "/static/openapi-schema.yml",
        dom_id: '#swagger-ui',
        presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
            request.headers['X-CSRFToken'] = "{{ csrf_token }}"
            return request;
        }
    })
</script>
</body>
</html>
{#src=#}